create table books (
     id integer primary key generated by default as identity,
     title varchar(200) null,
     author varchar(200) null,
     price integer null,
     rating integer null,
     creation_date date null,
     update_date date null
);